# Generated by Django 3.2 on 2021-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('userid', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(max_length=50)),
                ('created', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
