# Generated by Django 3.2 on 2021-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pidjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='btw_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
