# Generated by Django 3.2 on 2021-04-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidjango', '0002_xuser_btw_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xuser',
            new_name='Yuser',
        ),
    ]
