# Generated by Django 3.2.2 on 2021-05-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidjango', '0010_auto_20210505_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
        migrations.DeleteModel(
            name='Xuser',
        ),
    ]
