# Generated by Django 3.2 on 2021-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='btw_number',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
    ]
