# Generated by Django 3.2 on 2021-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0002_xuser_btw_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='coc_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuser',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
    ]
