# Generated by Django 3.2 on 2021-04-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0003_auto_20210427_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='btw_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='coc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='last_login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('address3', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(choices=[('nl', 'Netherlands'), ('be', 'Belgium'), ('ae', 'United Arabic Emirates'), ('uk', 'United Kingdom'), ('us', 'United States')], default='nl', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('btw_number', models.CharField(blank=True, max_length=50)),
                ('coc_number', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('xuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xx.xuser')),
            ],
        ),
    ]
