# Generated by Django 3.2 on 2021-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0004_auto_20210428_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('nl', 'Netherlands'), ('be', 'Belgium'), ('ae', 'United Arabic Emirates'), ('uk', 'United Kingdom'), ('us', 'United States')], default='nl', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Dutch'), ('en', 'English')], max_length=2),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='last_login',
            field=models.DateTimeField(blank=True),
        ),
    ]
