# Generated by Django 3.2 on 2021-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0006_auto_20210502_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
