# Generated by Django 3.2.2 on 2021-05-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0010_auto_20210513_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpi',
            name='xuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xx.xuser'),
            preserve_default=False,
        ),
    ]
