# Generated by Django 3.2.2 on 2021-05-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0011_rpi_xuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computernr', models.CharField(max_length=24)),
                ('activation_code', models.CharField(blank=True, max_length=12, null=True)),
                ('softwareVersion', models.CharField(default='00000', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rpi',
            name='activation_code',
        ),
    ]
