# Generated by Django 3.2.2 on 2021-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0013_auto_20210513_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrpi',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
