# Generated by Django 3.2.2 on 2021-05-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0014_newrpi_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrpi',
            old_name='softwareVersion',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='rpi',
            old_name='softwareVersion',
            new_name='version',
        ),
    ]
