# Generated by Django 3.2.2 on 2021-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0015_auto_20210514_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpiclicommand',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
