# Generated by Django 3.2.2 on 2021-05-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0017_alter_newnetwork_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newnetwork',
            old_name='password',
            new_name='psk',
        ),
        migrations.RemoveField(
            model_name='newnetwork',
            name='ssid',
        ),
    ]
