# Generated by Django 3.2.2 on 2021-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0019_auto_20210516_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpi',
            name='last_reboot',
            field=models.DateTimeField(blank=True, max_length=24, null=True),
        ),
    ]
