# Generated by Django 3.2.2 on 2021-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0020_alter_rpi_last_reboot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuser',
            name='failed_logins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('regular', 'regular')], default='regular', max_length=12),
        ),
    ]
