# Generated by Django 3.2.2 on 2021-05-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0022_auto_20210523_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=66, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=66, null=True)),
                ('message_new_user', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='xuser',
            name='last_updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
