# Generated by Django 3.2.2 on 2021-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0023_auto_20210527_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='free_period_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xuser',
            name='to_date',
            field=models.DateTimeField(blank=True, default='2021-05-22'),
        ),
        migrations.AlterField(
            model_name='rpi',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
