# Generated by Django 3.2.2 on 2021-05-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0024_auto_20210529_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xuser',
            old_name='to_date',
            new_name='support_end_date',
        ),
    ]
