# Generated by Django 3.2.2 on 2021-05-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0025_rename_to_date_xuser_support_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('command', models.CharField(max_length=500)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.AddField(
            model_name='rpi',
            name='id_rsa_pub',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
    ]
