# Generated by Django 3.2.2 on 2021-05-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0026_auto_20210530_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicommand',
            name='code',
            field=models.CharField(max_length=18),
        ),
    ]
