# Generated by Django 3.2.2 on 2021-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0028_alter_rpi_id_rsa_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='password2',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
